insert into brand (brandID, name, summary) values (1, 'CyberSolutions', null);
insert into brand (brandID, name, summary) values (2, 'SmartWave', null);
insert into brand (brandID, name, summary) values (3, 'CyberSolutions', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into brand (brandID, name, summary) values (4, 'QuantumTech', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into brand (brandID, name, summary) values (5, 'DigitalPulse', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into brand (brandID, name, summary) values (6, 'ByteTech', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into brand (brandID, name, summary) values (7, 'QuantumTech', null);
insert into brand (brandID, name, summary) values (8, 'InnoTech', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into brand (brandID, name, summary) values (9, 'ByteTech', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.');
insert into brand (brandID, name, summary) values (10, 'GigaGadgets', null);
insert into brand (brandID, name, summary) values (11, 'DigitalPulse', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into brand (brandID, name, summary) values (12, 'SmartWave', 'In congue. Etiam justo. Etiam pretium iaculis justo.');
insert into brand (brandID, name, summary) values (13, 'SmartWave', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into brand (brandID, name, summary) values (14, 'TechNova', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into brand (brandID, name, summary) values (15, 'ElectroTech', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into brand (brandID, name, summary) values (16, 'InnoTech', null);
insert into brand (brandID, name, summary) values (17, 'FuturTech', null);
insert into brand (brandID, name, summary) values (18, 'ByteTech', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into brand (brandID, name, summary) values (19, 'TechNova', null);
insert into brand (brandID, name, summary) values (20, 'ElectroTech', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into brand (brandID, name, summary) values (21, 'DigitalPulse', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into brand (brandID, name, summary) values (22, 'TechNova', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into brand (brandID, name, summary) values (23, 'QuantumTech', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.');
insert into brand (brandID, name, summary) values (24, 'CyberSolutions', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.');
insert into brand (brandID, name, summary) values (25, 'ByteTech', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into brand (brandID, name, summary) values (26, 'SmartWave', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into brand (brandID, name, summary) values (27, 'ElectroTech', null);
insert into brand (brandID, name, summary) values (28, 'CyberSolutions', null);
insert into brand (brandID, name, summary) values (29, 'ElectroTech', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into brand (brandID, name, summary) values (30, 'TechNova', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
